<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-SmsNotificator-33c8810e-14c4-4358-942b-d440b6c7e400</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="mainsms_official" Version="2.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0-rc.1.25451.107"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
      <ProjectReference Include="..\RabbitMqModule\RabbitMqModule.csproj" />
    </ItemGroup>
</Project>
